version: '3'

services:

    php:
        container_name: "${APP_SLUG}-php"
        build: .
        ports:
            - "${APP_PORT}:${APP_PORT}"

    redis:
        container_name: "${APP_SLUG}-redis"
        image: redis:alpine
        ports:
            - "6379:6379"

    redis-commander:
        container_name: "${APP_SLUG}-redis-commander"
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"

    mariadb:
        container_name: "${APP_NAME}-mariadb"
        image: mariadb
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: swoole